(function (global) {
  global.WOODCASE_PRODUCTS = [
    {
      id: "malm",
      name: "MALM",
      category: "Beds",
      section: "bed",
      price: "Rs. 39,000",
      copy: "A queen-size bed of reclaimed teak, oak weaving, and iron. The handmade frame is built for daily use, with a quiet modern profile that works as both a centrepiece and extra storage.",
      dimensions: "200 × 66 × 201 cm",
      materials: "Reclaimed teak, oak weave, iron",
      photoA: "../images/Products/Bed/bed 1.0.png",
      photoB: "../images/Products/Bed/bed 1.1.png",
    },
    {
      id: "berri",
      name: "BERRI",
      category: "Beds",
      section: "bed",
      price: "Rs. 46,000",
      copy: "A wider teak frame with a lower headboard, made for rooms that need the bed to sit quietly against the wall. Woven panels keep the mass light.",
      dimensions: "210 × 70 × 190 cm",
      materials: "Reclaimed teak, oak weave, iron",
      photoA: "../images/Products/Bed/bed 2.0.png",
      photoB: "../images/Products/Bed/bed 2.1.png",
    },
    {
      id: "kora",
      name: "KORA",
      category: "Beds",
      section: "bed",
      price: "Rs. 55,000",
      copy: "A taller storage bed with drawers in the base. The joinery is left visible, the same detail used on Artisan tables.",
      dimensions: "205 × 80 × 210 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Bed/bed 3.0.png",
      photoB: "../images/Products/Bed/bed 3.1.png",
    },
    {
      id: "vela",
      name: "VELA",
      category: "Beds",
      section: "bed",
      price: "Rs. 72,000",
      copy: "The largest bed in the line, with a full woven headboard and a teak plinth. Made for a main bedroom that can take a heavier piece.",
      dimensions: "220 × 85 × 220 cm",
      materials: "Reclaimed teak, coconut weave, iron",
      photoA: "../images/Products/Bed/bed 4.0.png",
      photoB: "../images/Products/Bed/bed 4.1.png",
    },
    {
      id: "nira",
      name: "NIRA",
      category: "Beds",
      section: "bed",
      price: "Rs. 45,000",
      copy: "A slimmer teak bed with open sides. Useful where the room is tight but you still want a solid wood frame.",
      dimensions: "200 × 55 × 195 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Bed/bed 5.0.png",
      photoB: "../images/Products/Bed/bed 5.1.png",
    },
    {
      id: "coco",
      name: "COCO",
      category: "Cabinets",
      section: "cabinet",
      price: "Rs. 19,000",
      copy: "Handmade coconut-weave doors on a reclaimed teak and iron frame. A compact cabinet for everyday storage, with the same warm material mix used across the collection.",
      dimensions: "90 × 45 × 160 cm",
      materials: "Reclaimed teak, coconut weave, iron",
      photoA: "../images/Products/Cabinet/cabinet 1.0.png",
      photoB: "../images/Products/Cabinet/cabinet 1.1.png",
    },
    {
      id: "aska",
      name: "ASKA",
      category: "Cabinets",
      section: "cabinet",
      price: "Rs. 30,000",
      copy: "A taller storage piece in reclaimed teak and iron, with woven doors that catch the light. Built as everyday storage that still reads as furniture, not a box against the wall.",
      dimensions: "90 × 45 × 180 cm",
      materials: "Reclaimed teak, coconut weave, iron",
      photoA: "../images/Products/Cabinet/cabinet 2.0.png",
      photoB: "../images/Products/Cabinet/cabinet 2.1.png",
    },
    {
      id: "tali",
      name: "TALI",
      category: "Cabinets",
      section: "cabinet",
      price: "Rs. 35,000",
      copy: "A sideboard with three woven doors and a long teak top. Made to hold tableware and still work as a surface in a dining room.",
      dimensions: "160 × 42 × 85 cm",
      materials: "Reclaimed teak, oak weave, iron",
      photoA: "../images/Products/Cabinet/cabinet 3.0.png",
      photoB: "../images/Products/Cabinet/cabinet 3.1.png",
    },
    {
      id: "mira",
      name: "MIRA",
      category: "Cabinets",
      section: "cabinet",
      price: "Rs. 25,000",
      copy: "A mid-height cabinet with open shelves beside a closed bay. Useful when some objects should stay on view.",
      dimensions: "120 × 40 × 140 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Cabinet/cabinet 4.0.png",
      photoB: "../images/Products/Cabinet/cabinet 4.1.png",
    },
    {
      id: "roku",
      name: "ROKU",
      category: "Cabinets",
      section: "cabinet",
      price: "Rs. 20,000",
      copy: "A narrow teak cabinet for a hallway or beside a bed. One door, one shelf, no extra hardware.",
      dimensions: "50 × 38 × 130 cm",
      materials: "Reclaimed teak, coconut weave, iron",
      photoA: "../images/Products/Cabinet/cabinet 5.0.png",
      photoB: "../images/Products/Cabinet/cabinet 5.1.png",
    },
    {
      id: "lina",
      name: "LINA",
      category: "Chairs",
      section: "chair",
      price: "Rs. 7,000",
      copy: "A dining chair with a woven seat and a light teak back. Stacks two high in the workshop; sits well at JOMA or KEEL.",
      dimensions: "48 × 52 × 82 cm",
      materials: "Reclaimed teak, oak weave",
      photoA: "../images/Products/Chair/Chair 1.0.png",
      photoB: "../images/Products/Chair/Chair 1.1.png",
    },
    {
      id: "peth",
      name: "PETH",
      category: "Chairs",
      section: "chair",
      price: "Rs. 9,000",
      copy: "A lounge chair with a deeper seat and iron sled legs. Meant for a corner, not the dining table.",
      dimensions: "62 × 70 × 78 cm",
      materials: "Reclaimed teak, coconut weave, iron",
      photoA: "../images/Products/Chair/Chair 2.0.png",
      photoB: "../images/Products/Chair/Chair 2.1.png",
    },
    {
      id: "sora",
      name: "SORA",
      category: "Chairs",
      section: "chair",
      price: "Rs. 15,000",
      copy: "An armchair with a wide woven back. The teak arms are rounded so it can sit away from a wall.",
      dimensions: "70 × 74 × 80 cm",
      materials: "Reclaimed teak, oak weave, iron",
      photoA: "../images/Products/Chair/Chair 3.0.png",
      photoB: "../images/Products/Chair/Chair 3.1.png",
    },
    {
      id: "kavi",
      name: "KAVI",
      category: "Chairs",
      section: "chair",
      price: "Rs. 11,000",
      copy: "A desk chair with a firmer seat and a low back. Made for a work table rather than a lounge.",
      dimensions: "50 × 54 × 84 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Chair/Chair 4.0.png",
      photoB: "../images/Products/Chair/Chair 4.1.png",
    },
    {
      id: "olan",
      name: "OLAN",
      category: "Chairs",
      section: "chair",
      price: "Rs. 18,000",
      copy: "A high-back chair with a full weave. Heavier than LINA, and meant as a single piece rather than a set of six.",
      dimensions: "58 × 68 × 110 cm",
      materials: "Reclaimed teak, coconut weave, iron",
      photoA: "../images/Products/Chair/Chair 5.0.png",
      photoB: "../images/Products/Chair/Chair 5.1.png",
    },
    {
      id: "alma",
      name: "ALMA",
      category: "Shelves",
      section: "shelve",
      price: "Rs. 14,000",
      copy: "A single wall shelf in reclaimed teak on a slim iron bracket. Works alone or in a run with RIFT and NEST.",
      dimensions: "90 × 22 × 18 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Shelves/shelves 1.0.png",
      photoB: "../images/Products/Shelves/shelves 1.1.png",
    },
    {
      id: "rift",
      name: "RIFT",
      category: "Shelves",
      section: "shelve",
      price: "Rs. 19,000",
      copy: "A two-tier wall unit from the Shelfmate system. The iron frame holds the teak boards off the wall so the composition can grow.",
      dimensions: "80 × 24 × 60 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Shelves/shelves 2.0.png",
      photoB: "../images/Products/Shelves/shelves 2.1.png",
    },
    {
      id: "nest",
      name: "NEST",
      category: "Shelves",
      section: "shelve",
      price: "Rs. 30,000",
      copy: "A larger wall composition with three boards of different lengths. Built as a finished set, not a single rail.",
      dimensions: "140 × 26 × 90 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Shelves/shelves 3.0.png",
      photoB: "../images/Products/Shelves/shelves 3.1.png",
    },
    {
      id: "plin",
      name: "PLIN",
      category: "Shelves",
      section: "shelve",
      price: "Rs. 25,000",
      copy: "A floor-standing shelf with a low plinth. Use it when you cannot fix into the wall.",
      dimensions: "100 × 30 × 160 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Shelves/shelves 4.0.png",
      photoB: "../images/Products/Shelves/shelves 4.1.png",
    },
    {
      id: "edge",
      name: "EDGE",
      category: "Shelves",
      section: "shelve",
      price: "Rs. 27,000",
      copy: "A corner shelf with two returns. Made for a room where a straight run would waste the junction.",
      dimensions: "70 × 70 × 140 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Shelves/shelves 5.0.png",
      photoB: "../images/Products/Shelves/shelves 5.1.png",
    },
    {
      id: "duna",
      name: "DUNA",
      category: "Sofas",
      section: "sofa",
      price: "Rs. 32,000",
      copy: "A two-seat sofa on a teak frame with a woven seat. Compact enough for a smaller sitting room.",
      dimensions: "160 × 78 × 78 cm",
      materials: "Reclaimed teak, oak weave, iron",
      photoA: "../images/Products/Sofa/sofa 1.0.png",
      photoB: "../images/Products/Sofa/sofa 1.1.png",
    },
    {
      id: "hale",
      name: "HALE",
      category: "Sofas",
      section: "sofa",
      price: "Rs. 45,000",
      copy: "A deeper three-seat frame with loose cushions. The teak arms stay uncovered so the wood stays on view.",
      dimensions: "200 × 86 × 80 cm",
      materials: "Reclaimed teak, cotton, iron",
      photoA: "../images/Products/Sofa/sofa 2.0.png",
      photoB: "../images/Products/Sofa/sofa 2.1.png",
    },
    {
      id: "mero",
      name: "MERO",
      category: "Sofas",
      section: "sofa",
      price: "Rs. 39,000",
      copy: "A daybed-length sofa with one raised end. Works as seating by day and a spare bed when needed.",
      dimensions: "190 × 80 × 72 cm",
      materials: "Reclaimed teak, oak weave",
      photoA: "../images/Products/Sofa/sofa 3.0.png",
      photoB: "../images/Products/Sofa/sofa 3.1.png",
    },
    {
      id: "arka",
      name: "ARKA",
      category: "Sofas",
      section: "sofa",
      price: "Rs. 60,000",
      copy: "The largest sofa, with a chaise on one side. Built as a single frame so the join does not sag.",
      dimensions: "260 × 160 × 80 cm",
      materials: "Reclaimed teak, cotton, iron",
      photoA: "../images/Products/Sofa/sofa 4.0.png",
      photoB: "../images/Products/Sofa/sofa 4.1.png",
    },
    {
      id: "sila",
      name: "SILA",
      category: "Sofas",
      section: "sofa",
      price: "Rs. 42,000",
      copy: "A straight three-seat sofa with a low back. Meant to sit in front of a window without blocking it.",
      dimensions: "210 × 82 × 74 cm",
      materials: "Reclaimed teak, coconut weave, iron",
      photoA: "../images/Products/Sofa/sofa 5.0.png",
      photoB: "../images/Products/Sofa/sofa 5.1.png",
    },
    {
      id: "joma",
      name: "JOMA",
      category: "Tables",
      section: "table",
      price: "Rs. 10,000",
      copy: "A small teak side table from the Artisan collection. The leg joinery is the same detail used on the larger dining tables.",
      dimensions: "45 × 45 × 50 cm",
      materials: "Reclaimed teak",
      photoA: "../images/Products/Tables/tables 1.0.png",
      photoB: "../images/Products/Tables/tables 1.1.png",
    },
    {
      id: "keel",
      name: "KEEL",
      category: "Tables",
      section: "table",
      price: "Rs. 12,000",
      copy: "A coffee table with a thick teak top and inset iron stretchers. Sized for DUNA or HALE.",
      dimensions: "110 × 60 × 40 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Tables/tables 2.0.png",
      photoB: "../images/Products/Tables/tables 2.1.png",
    },
    {
      id: "brun",
      name: "BRUN",
      category: "Tables",
      section: "table",
      price: "Rs. 15,000",
      copy: "A console for a hall or behind a sofa. Narrow enough to keep a walkway clear.",
      dimensions: "140 × 35 × 80 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Tables/tables 3.0.png",
      photoB: "../images/Products/Tables/tables 3.1.png",
    },
    {
      id: "ford",
      name: "FORD",
      category: "Tables",
      section: "table",
      price: "Rs. 25,000",
      copy: "A dining table for six, with the Artisan leg joint left proud of the apron. The top is a single-thickness teak slab.",
      dimensions: "180 × 90 × 75 cm",
      materials: "Reclaimed teak",
      photoA: "../images/Products/Tables/tables 4.0.png",
      photoB: "../images/Products/Tables/tables 4.1.png",
    },
    {
      id: "wisp",
      name: "WISP",
      category: "Tables",
      section: "table",
      price: "Rs. 27,000",
      copy: "A longer dining table for eight. The same joinery as FORD, scaled so the top does not cup.",
      dimensions: "220 × 95 × 75 cm",
      materials: "Reclaimed teak",
      photoA: "../images/Products/Tables/tables 5.0.png",
      photoB: "../images/Products/Tables/tables 5.1.png",
    },
    {
      id: "rulo",
      name: "RULO",
      category: "Trolleys",
      section: "trolley",
      price: "Rs. 10,000",
      copy: "A two-tier serving trolley on iron castors. The teak trays lift off for cleaning.",
      dimensions: "70 × 40 × 80 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Trolley/Trolley 1.0.png",
      photoB: "../images/Products/Trolley/Trolley 1.1.png",
    },
    {
      id: "tabi",
      name: "TABI",
      category: "Trolleys",
      section: "trolley",
      price: "Rs. 12,000",
      copy: "A taller bar trolley with a rail on the top tray. Made to hold glasses without them sliding.",
      dimensions: "65 × 38 × 90 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Trolley/Trolley 2.0.png",
      photoB: "../images/Products/Trolley/Trolley 2.1.png",
    },
    {
      id: "moci",
      name: "MOCI",
      category: "Trolleys",
      section: "trolley",
      price: "Rs. 15,000",
      copy: "A kitchen trolley with a deeper bottom shelf for pans. The top is left unfinished so it can take a hot pot.",
      dimensions: "80 × 45 × 85 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Trolley/Trolley 3.0.png",
      photoB: "../images/Products/Trolley/Trolley 3.1.png",
    },
    {
      id: "giri",
      name: "GIRI",
      category: "Trolleys",
      section: "trolley",
      price: "Rs. 25,000",
      copy: "A wider hospitality trolley with three tiers. Built for a dining room that serves from the piece itself.",
      dimensions: "100 × 48 × 88 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Trolley/Trolley 4.0.png",
      photoB: "../images/Products/Trolley/Trolley 4.1.png",
    },
    {
      id: "pena",
      name: "PENA",
      category: "Trolleys",
      section: "trolley",
      price: "Rs. 27,000",
      copy: "A desk-height trolley that can sit beside a sofa as a moving side table. One drawer under the top tray.",
      dimensions: "60 × 40 × 70 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Trolley/Trolley 5.0.png",
      photoB: "../images/Products/Trolley/Trolley 5.1.png",
    },
    {
      id: "kast",
      name: "KAST",
      category: "Wardrobes",
      section: "wardrobe",
      price: "Rs. 42,000",
      copy: "A two-door wardrobe in reclaimed teak with a hanging rail and one shelf. The doors are plain so the grain stays the detail.",
      dimensions: "120 × 58 × 200 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Wardrobe/wardrobe 1.0.png",
      photoB: "../images/Products/Wardrobe/wardrobe 1.1.png",
    },
    {
      id: "loom",
      name: "LOOM",
      category: "Wardrobes",
      section: "wardrobe",
      price: "Rs. 29,000",
      copy: "A smaller wardrobe with woven door panels. Sized for a guest room rather than a full closet.",
      dimensions: "90 × 55 × 180 cm",
      materials: "Reclaimed teak, coconut weave, iron",
      photoA: "../images/Products/Wardrobe/wardrobe 2.0.png",
      photoB: "../images/Products/Wardrobe/wardrobe 2.1.png",
    },
    {
      id: "vest",
      name: "VEST",
      category: "Wardrobes",
      section: "wardrobe",
      price: "Rs. 30,000",
      copy: "An open wardrobe with a rail and a low drawer. Use it when you want clothes on view, or in a dressing area.",
      dimensions: "110 × 50 × 190 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Wardrobe/wardrobe 3.0.png",
      photoB: "../images/Products/Wardrobe/wardrobe 3.1.png",
    },
    {
      id: "gran",
      name: "GRAN",
      category: "Wardrobes",
      section: "wardrobe",
      price: "Rs. 78,000",
      copy: "The largest wardrobe, with four doors and a central set of drawers. Built as one carcass so the doors stay aligned.",
      dimensions: "220 × 62 × 210 cm",
      materials: "Reclaimed teak, iron",
      photoA: "../images/Products/Wardrobe/wardrobe 4.0.png",
      photoB: "../images/Products/Wardrobe/wardrobe 4.1.png",
    },
    {
      id: "nook",
      name: "NOOK",
      category: "Wardrobes",
      section: "wardrobe",
      price: "Rs. 21,000",
      copy: "A single-door wardrobe for a tight alcove. One rail, one high shelf, no extra bays.",
      dimensions: "60 × 55 × 190 cm",
      materials: "Reclaimed teak, oak weave, iron",
      photoA: "../images/Products/Wardrobe/wardrobe 5.0.png",
      photoB: "../images/Products/Wardrobe/wardrobe 5.1.png",
    },
  ];

  global.WOODCASE_PRODUCTS.byId = function (id) {
    return global.WOODCASE_PRODUCTS.filter(function (item) {
      return item.id === id;
    })[0];
  };
})(window);
